// Embeds the two canonical Agent Setup installer bodies as runtime-neutral
// string constants in `src/script-assets.generated.ts`. The package serves
// those bodies without a `?raw` loader or filesystem access, so every host
// runtime consumes one identical source; the generated file is checked in.
//
// Run `pnpm --filter @floway-dev/agent-setup run generate-assets` to (re)write
// the generated module; pass `--check` to fail non-zero when the checked-in
// output has drifted from the canonical installers (a pre-deploy / review
// gate). Output is deterministic: `JSON.stringify` fixes the encoded bytes for
// a given input.
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = resolve(HERE, '..');
const SH_PATH = resolve(PACKAGE_ROOT, 'installers/setup.sh');
const PS1_PATH = resolve(PACKAGE_ROOT, 'installers/setup.ps1');
const GENERATED_PATH = resolve(PACKAGE_ROOT, 'src/script-assets.generated.ts');

const buildGeneratedSource = async (): Promise<string> => {
  const [sh, ps1] = await Promise.all([readFile(SH_PATH, 'utf8'), readFile(PS1_PATH, 'utf8')]);
  return `// GENERATED by scripts/generate-assets.ts — do not edit by hand.
//
// The fixed installer bodies for the public setup scripts, embedded verbatim
// from installers/{setup.sh,setup.ps1}. The route factory prepends a per-request
// language-native assignment prefix and serves the concatenation. Regenerate
// after editing either canonical installer:
// \`pnpm --filter @floway-dev/agent-setup run generate-assets\`.

export const SETUP_SH_BODY = ${JSON.stringify(sh)};

export const SETUP_PS1_BODY = ${JSON.stringify(ps1)};
`;
};

const expected = await buildGeneratedSource();

if (process.argv.includes('--check')) {
  const actual = await readFile(GENERATED_PATH, 'utf8').catch(() => null);
  if (actual !== expected) {
    console.error('script-assets.generated.ts is out of date with the canonical installers.');
    console.error('Run: pnpm --filter @floway-dev/agent-setup run generate-assets');
    process.exit(1);
  }
  console.log('script-assets.generated.ts is up to date.');
} else {
  await writeFile(GENERATED_PATH, expected);
  console.log(`Wrote ${GENERATED_PATH}`);
}
