/* eslint-disable */
// GENERATED by scripts/generate-agent-setup-assets.ts — do not edit by hand.
//
// The fixed installer bodies for the public setup scripts, embedded verbatim
// from control-plane/agent-setup/scripts/{setup.sh,setup.ps1}. The gateway
// prepends a per-request language-native assignment prefix and serves the
// concatenation. Regenerate after editing either canonical script:
// `pnpm jiti scripts/generate-agent-setup-assets.ts`.

export const SETUP_SH_BODY = "# Floway agent setup installer (POSIX shell).\n#\n# Fixed, checked-in body. The language-native assignment prefix (the FLOWAY_*\n# variables and a trace-suppressing `set +x`) is prepended per request by the\n# gateway, so this file starts straight at the installer logic with no shebang.\n# The phase markers below are the seams Tasks 7/8 fill in; until then the body\n# is a valid no-op skeleton so an early `curl ... | sh` does nothing harmful.\n\nset -eu\n\n# --- phase: preflight ---\n# --- phase: claude-code ---\n# --- phase: codex ---\n# --- phase: verify ---\n\necho 'Floway agent setup is not implemented in this build yet.' >&2\n";

export const SETUP_PS1_BODY = "# Floway agent setup installer (PowerShell).\n#\n# Fixed, checked-in body. The language-native assignment prefix (the $Floway*\n# variables and a trace-suppressing `Set-PSDebug -Off`) is prepended per\n# request by the gateway, so this file starts straight at the installer logic.\n# The phase markers below are the seams Tasks 7/8 fill in; until then the body\n# is a valid no-op skeleton so an early `irm ... | iex` does nothing harmful.\n\n$ErrorActionPreference = 'Stop'\n\n# --- phase: preflight ---\n# --- phase: claude-code ---\n# --- phase: codex ---\n# --- phase: verify ---\n\nWrite-Host 'Floway agent setup is not implemented in this build yet.'\n";
