// Embeds the two canonical Agent Setup script bodies as runtime-neutral string
// constants in the gateway's `script-assets.generated.ts`. The gateway serves
// those bodies without a `?raw` loader or filesystem access, so Wrangler and
// Node consume one identical source; the generated file is checked in.
//
// Run `pnpm jiti scripts/generate-agent-setup-assets.ts` to (re)write the
// generated module; pass `--check` to fail non-zero when the checked-in output
// has drifted from the canonical scripts (a pre-deploy / review gate). Output
// is deterministic: `JSON.stringify` fixes the encoded bytes for a given input.
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ASSET_DIR = resolve(HERE, '..', 'packages/gateway/src/control-plane/agent-setup');
const SH_PATH = resolve(ASSET_DIR, 'scripts/setup.sh');
const PS1_PATH = resolve(ASSET_DIR, 'scripts/setup.ps1');
const GENERATED_PATH = resolve(ASSET_DIR, 'script-assets.generated.ts');

const buildGeneratedSource = async (): Promise<string> => {
  const [sh, ps1] = await Promise.all([readFile(SH_PATH, 'utf8'), readFile(PS1_PATH, 'utf8')]);
  return `// GENERATED by scripts/generate-agent-setup-assets.ts — do not edit by hand.
//
// The fixed installer bodies for the public setup scripts, embedded verbatim
// from control-plane/agent-setup/scripts/{setup.sh,setup.ps1}. The gateway
// prepends a per-request language-native assignment prefix and serves the
// concatenation. Regenerate after editing either canonical script:
// \`pnpm jiti scripts/generate-agent-setup-assets.ts\`.

export const SETUP_SH_BODY = ${JSON.stringify(sh)};

export const SETUP_PS1_BODY = ${JSON.stringify(ps1)};
`;
};

const expected = await buildGeneratedSource();

if (process.argv.includes('--check')) {
  const actual = await readFile(GENERATED_PATH, 'utf8').catch(() => null);
  if (actual !== expected) {
    console.error('script-assets.generated.ts is out of date with the canonical setup scripts.');
    console.error('Run: pnpm jiti scripts/generate-agent-setup-assets.ts');
    process.exit(1);
  }
  console.log('script-assets.generated.ts is up to date.');
} else {
  await writeFile(GENERATED_PATH, expected);
  console.log(`Wrote ${GENERATED_PATH}`);
}
